// Package agent implements a general-purpose Claude tool-use agent for the
// Telegram bot: unlike internal/ai's single forced-tool ClassifyIntent, this
// runs a real multi-tool loop (auto tool choice, up to maxToolIterations
// round-trips) over Billz reports (internal/reports) and task management
// (internal/tasks), with short per-chat conversation memory so the bot can
// ask a clarifying question and understand the follow-up.
package agent

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/anthropics/anthropic-sdk-go/option"

	"fahriddin-ai/internal/billz"
	"fahriddin-ai/internal/summary"
	"fahriddin-ai/internal/tasks"
)

const (
	maxToolIterations = 6
	historyTurnLimit  = 16
	maxTokensPerTurn  = 1536
	maxTokensWrapUp   = 1024
)

// Attachment is a file generated by a tool call (currently only
// generate_excel_report) that rides alongside the agent's text reply,
// out-of-band from the Anthropic API (tool_result content can't carry
// binary data).
type Attachment struct {
	Filename string
	Bytes    []byte
}

// Result is the agent's reply to one Handle call.
type Result struct {
	Text       string
	Attachment *Attachment
}

// Agent wraps its own Anthropic client (mirroring internal/ai.Client's
// construction, not sharing internal/ai's internals) plus everything the
// tool dispatch needs to call into the rest of the app.
type Agent struct {
	client  anthropic.Client
	model   anthropic.Model
	billz   *billz.Client // optional: nil disables all Billz-backed tools
	tasks   *tasks.Store
	summary *summary.Builder
	db      *sql.DB
	loc     *time.Location
	log     *slog.Logger
}

func New(apiKey, model string, billzClient *billz.Client, taskStore *tasks.Store, summaryBuilder *summary.Builder, db *sql.DB, loc *time.Location, log *slog.Logger) *Agent {
	return &Agent{
		client:  anthropic.NewClient(option.WithAPIKey(apiKey)),
		model:   anthropic.Model(model),
		billz:   billzClient,
		tasks:   taskStore,
		summary: summaryBuilder,
		db:      db,
		loc:     loc,
		log:     log,
	}
}

// Handle runs the full tool-use loop for one incoming message: loads recent
// conversation history for chatID, lets Claude call zero or more tools
// (possibly several per turn, possibly across several turns), and returns
// the final text reply plus an optional file attachment. Clarifying
// questions need no special handling — Claude just replies with text and no
// tool call that turn, and the persisted history makes the user's next
// message resolvable as an answer to that question.
func (a *Agent) Handle(ctx context.Context, chatID int64, userText string) (Result, error) {
	now := time.Now().In(a.loc)

	history, err := a.loadHistory(ctx, chatID, historyTurnLimit)
	if err != nil {
		a.log.Warn("agent: load history failed", "err", err)
		history = nil
	}
	history = append(history, anthropic.NewUserMessage(anthropic.NewTextBlock(userText)))
	if err := a.saveTurn(ctx, chatID, "user", userText); err != nil {
		a.log.Warn("agent: save user turn failed", "err", err)
	}

	sys := []anthropic.TextBlockParam{{Text: systemPrompt(now)}}

	var toolsUsed []string
	var attachment *Attachment
	var finalText string

	for i := 0; i < maxToolIterations; i++ {
		msg, err := a.client.Messages.New(ctx, anthropic.MessageNewParams{
			Model:     a.model,
			MaxTokens: maxTokensPerTurn,
			System:    sys,
			Messages:  history,
			Tools:     allTools,
		})
		if err != nil {
			a.logQuery(ctx, chatID, userText, toolsUsed, false, err.Error())
			return Result{}, fmt.Errorf("claude request: %w", err)
		}
		history = append(history, toAssistantParam(msg))

		if msg.StopReason != anthropic.StopReasonToolUse {
			finalText = extractText(msg)
			break
		}

		var resultBlocks []anthropic.ContentBlockParamUnion
		for _, block := range msg.Content {
			if block.Type != "tool_use" {
				continue
			}
			toolsUsed = append(toolsUsed, block.Name)
			resultText, att, isErr := a.dispatchTool(ctx, block.Name, block.Input, now)
			if att != nil {
				attachment = att
			}
			resultBlocks = append(resultBlocks, anthropic.NewToolResultBlock(block.ID, resultText, isErr))
		}
		history = append(history, anthropic.NewUserMessage(resultBlocks...))
	}

	if finalText == "" {
		// Ran out of iterations while still tool-calling — force a
		// text-only wrap-up over whatever tool results are already in
		// history instead of silently failing.
		msg, err := a.client.Messages.New(ctx, anthropic.MessageNewParams{
			Model:     a.model,
			MaxTokens: maxTokensWrapUp,
			System:    sys,
			Messages:  history,
		})
		if err != nil {
			a.logQuery(ctx, chatID, userText, toolsUsed, false, err.Error())
			return Result{}, fmt.Errorf("claude wrap-up request: %w", err)
		}
		finalText = extractText(msg)
	}
	if finalText == "" {
		finalText = "Uzr, hozir aniq javob bera olmadim. Boshqacharoq so'rab ko'ring."
	}

	if err := a.saveTurn(ctx, chatID, "assistant", finalText); err != nil {
		a.log.Warn("agent: save assistant turn failed", "err", err)
	}
	a.logQuery(ctx, chatID, userText, toolsUsed, true, "")

	return Result{Text: finalText, Attachment: attachment}, nil
}

// toAssistantParam converts a response Message's content blocks back into
// request-shaped blocks so it can be appended to history for the next
// turn — the SDK has no built-in response->request converter, so this
// keeps only the block types that matter for our loop (text and tool_use;
// thinking/redacted_thinking blocks are dropped, since this agent doesn't
// request extended thinking).
func toAssistantParam(msg *anthropic.Message) anthropic.MessageParam {
	blocks := make([]anthropic.ContentBlockParamUnion, 0, len(msg.Content))
	for _, block := range msg.Content {
		switch block.Type {
		case "text":
			blocks = append(blocks, anthropic.NewTextBlock(block.Text))
		case "tool_use":
			blocks = append(blocks, anthropic.NewToolUseBlock(block.ID, block.Input, block.Name))
		}
	}
	return anthropic.NewAssistantMessage(blocks...)
}

func extractText(msg *anthropic.Message) string {
	var sb strings.Builder
	for _, block := range msg.Content {
		if block.Type == "text" {
			sb.WriteString(block.Text)
		}
	}
	return stripMarkdown(sb.String())
}

// stripMarkdown mirrors internal/ai's helper of the same name — both
// packages independently call the Anthropic API and need identical
// plain-text formatting, since Telegram doesn't render markdown.
func stripMarkdown(s string) string {
	s = strings.ReplaceAll(s, "**", "")
	s = strings.ReplaceAll(s, "__", "")
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		trimmed := strings.TrimLeft(line, "#")
		if trimmed != line {
			lines[i] = strings.TrimSpace(trimmed)
		}
	}
	return strings.Join(lines, "\n")
}

func unmarshalArgs(input json.RawMessage, dst any) error {
	if len(input) == 0 {
		return nil
	}
	return json.Unmarshal(input, dst)
}
